
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BuyerStats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BuyerStats
 * 
 */
export type BuyerStatsModel = runtime.Types.Result.DefaultSelection<Prisma.$BuyerStatsPayload>

export type AggregateBuyerStats = {
  _count: BuyerStatsCountAggregateOutputType | null
  _avg: BuyerStatsAvgAggregateOutputType | null
  _sum: BuyerStatsSumAggregateOutputType | null
  _min: BuyerStatsMinAggregateOutputType | null
  _max: BuyerStatsMaxAggregateOutputType | null
}

export type BuyerStatsAvgAggregateOutputType = {
  purchases: number | null
  totalSpent: number | null
}

export type BuyerStatsSumAggregateOutputType = {
  purchases: number | null
  totalSpent: number | null
}

export type BuyerStatsMinAggregateOutputType = {
  id: string | null
  userId: string | null
  purchases: number | null
  totalSpent: number | null
}

export type BuyerStatsMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  purchases: number | null
  totalSpent: number | null
}

export type BuyerStatsCountAggregateOutputType = {
  id: number
  userId: number
  purchases: number
  totalSpent: number
  _all: number
}


export type BuyerStatsAvgAggregateInputType = {
  purchases?: true
  totalSpent?: true
}

export type BuyerStatsSumAggregateInputType = {
  purchases?: true
  totalSpent?: true
}

export type BuyerStatsMinAggregateInputType = {
  id?: true
  userId?: true
  purchases?: true
  totalSpent?: true
}

export type BuyerStatsMaxAggregateInputType = {
  id?: true
  userId?: true
  purchases?: true
  totalSpent?: true
}

export type BuyerStatsCountAggregateInputType = {
  id?: true
  userId?: true
  purchases?: true
  totalSpent?: true
  _all?: true
}

export type BuyerStatsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuyerStats to aggregate.
   */
  where?: Prisma.BuyerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuyerStats to fetch.
   */
  orderBy?: Prisma.BuyerStatsOrderByWithRelationInput | Prisma.BuyerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BuyerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuyerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuyerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BuyerStats
  **/
  _count?: true | BuyerStatsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BuyerStatsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BuyerStatsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BuyerStatsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BuyerStatsMaxAggregateInputType
}

export type GetBuyerStatsAggregateType<T extends BuyerStatsAggregateArgs> = {
      [P in keyof T & keyof AggregateBuyerStats]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBuyerStats[P]>
    : Prisma.GetScalarType<T[P], AggregateBuyerStats[P]>
}




export type BuyerStatsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BuyerStatsWhereInput
  orderBy?: Prisma.BuyerStatsOrderByWithAggregationInput | Prisma.BuyerStatsOrderByWithAggregationInput[]
  by: Prisma.BuyerStatsScalarFieldEnum[] | Prisma.BuyerStatsScalarFieldEnum
  having?: Prisma.BuyerStatsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BuyerStatsCountAggregateInputType | true
  _avg?: BuyerStatsAvgAggregateInputType
  _sum?: BuyerStatsSumAggregateInputType
  _min?: BuyerStatsMinAggregateInputType
  _max?: BuyerStatsMaxAggregateInputType
}

export type BuyerStatsGroupByOutputType = {
  id: string
  userId: string
  purchases: number
  totalSpent: number
  _count: BuyerStatsCountAggregateOutputType | null
  _avg: BuyerStatsAvgAggregateOutputType | null
  _sum: BuyerStatsSumAggregateOutputType | null
  _min: BuyerStatsMinAggregateOutputType | null
  _max: BuyerStatsMaxAggregateOutputType | null
}

type GetBuyerStatsGroupByPayload<T extends BuyerStatsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BuyerStatsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BuyerStatsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BuyerStatsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BuyerStatsGroupByOutputType[P]>
      }
    >
  >



export type BuyerStatsWhereInput = {
  AND?: Prisma.BuyerStatsWhereInput | Prisma.BuyerStatsWhereInput[]
  OR?: Prisma.BuyerStatsWhereInput[]
  NOT?: Prisma.BuyerStatsWhereInput | Prisma.BuyerStatsWhereInput[]
  id?: Prisma.StringFilter<"BuyerStats"> | string
  userId?: Prisma.StringFilter<"BuyerStats"> | string
  purchases?: Prisma.IntFilter<"BuyerStats"> | number
  totalSpent?: Prisma.FloatFilter<"BuyerStats"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type BuyerStatsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  purchases?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type BuyerStatsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.BuyerStatsWhereInput | Prisma.BuyerStatsWhereInput[]
  OR?: Prisma.BuyerStatsWhereInput[]
  NOT?: Prisma.BuyerStatsWhereInput | Prisma.BuyerStatsWhereInput[]
  purchases?: Prisma.IntFilter<"BuyerStats"> | number
  totalSpent?: Prisma.FloatFilter<"BuyerStats"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId">

export type BuyerStatsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  purchases?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
  _count?: Prisma.BuyerStatsCountOrderByAggregateInput
  _avg?: Prisma.BuyerStatsAvgOrderByAggregateInput
  _max?: Prisma.BuyerStatsMaxOrderByAggregateInput
  _min?: Prisma.BuyerStatsMinOrderByAggregateInput
  _sum?: Prisma.BuyerStatsSumOrderByAggregateInput
}

export type BuyerStatsScalarWhereWithAggregatesInput = {
  AND?: Prisma.BuyerStatsScalarWhereWithAggregatesInput | Prisma.BuyerStatsScalarWhereWithAggregatesInput[]
  OR?: Prisma.BuyerStatsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BuyerStatsScalarWhereWithAggregatesInput | Prisma.BuyerStatsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BuyerStats"> | string
  userId?: Prisma.StringWithAggregatesFilter<"BuyerStats"> | string
  purchases?: Prisma.IntWithAggregatesFilter<"BuyerStats"> | number
  totalSpent?: Prisma.FloatWithAggregatesFilter<"BuyerStats"> | number
}

export type BuyerStatsCreateInput = {
  id?: string
  purchases?: number
  totalSpent?: number
  user: Prisma.UserCreateNestedOneWithoutBuyerStatsInput
}

export type BuyerStatsUncheckedCreateInput = {
  id?: string
  userId: string
  purchases?: number
  totalSpent?: number
}

export type BuyerStatsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  purchases?: Prisma.IntFieldUpdateOperationsInput | number
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutBuyerStatsNestedInput
}

export type BuyerStatsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  purchases?: Prisma.IntFieldUpdateOperationsInput | number
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type BuyerStatsCreateManyInput = {
  id?: string
  userId: string
  purchases?: number
  totalSpent?: number
}

export type BuyerStatsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  purchases?: Prisma.IntFieldUpdateOperationsInput | number
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type BuyerStatsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  purchases?: Prisma.IntFieldUpdateOperationsInput | number
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type BuyerStatsNullableScalarRelationFilter = {
  is?: Prisma.BuyerStatsWhereInput | null
  isNot?: Prisma.BuyerStatsWhereInput | null
}

export type BuyerStatsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  purchases?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
}

export type BuyerStatsAvgOrderByAggregateInput = {
  purchases?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
}

export type BuyerStatsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  purchases?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
}

export type BuyerStatsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  purchases?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
}

export type BuyerStatsSumOrderByAggregateInput = {
  purchases?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
}

export type BuyerStatsCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BuyerStatsCreateWithoutUserInput, Prisma.BuyerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.BuyerStatsCreateOrConnectWithoutUserInput
  connect?: Prisma.BuyerStatsWhereUniqueInput
}

export type BuyerStatsUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BuyerStatsCreateWithoutUserInput, Prisma.BuyerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.BuyerStatsCreateOrConnectWithoutUserInput
  connect?: Prisma.BuyerStatsWhereUniqueInput
}

export type BuyerStatsUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BuyerStatsCreateWithoutUserInput, Prisma.BuyerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.BuyerStatsCreateOrConnectWithoutUserInput
  upsert?: Prisma.BuyerStatsUpsertWithoutUserInput
  disconnect?: Prisma.BuyerStatsWhereInput | boolean
  delete?: Prisma.BuyerStatsWhereInput | boolean
  connect?: Prisma.BuyerStatsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BuyerStatsUpdateToOneWithWhereWithoutUserInput, Prisma.BuyerStatsUpdateWithoutUserInput>, Prisma.BuyerStatsUncheckedUpdateWithoutUserInput>
}

export type BuyerStatsUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BuyerStatsCreateWithoutUserInput, Prisma.BuyerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.BuyerStatsCreateOrConnectWithoutUserInput
  upsert?: Prisma.BuyerStatsUpsertWithoutUserInput
  disconnect?: Prisma.BuyerStatsWhereInput | boolean
  delete?: Prisma.BuyerStatsWhereInput | boolean
  connect?: Prisma.BuyerStatsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BuyerStatsUpdateToOneWithWhereWithoutUserInput, Prisma.BuyerStatsUpdateWithoutUserInput>, Prisma.BuyerStatsUncheckedUpdateWithoutUserInput>
}

export type BuyerStatsCreateWithoutUserInput = {
  id?: string
  purchases?: number
  totalSpent?: number
}

export type BuyerStatsUncheckedCreateWithoutUserInput = {
  id?: string
  purchases?: number
  totalSpent?: number
}

export type BuyerStatsCreateOrConnectWithoutUserInput = {
  where: Prisma.BuyerStatsWhereUniqueInput
  create: Prisma.XOR<Prisma.BuyerStatsCreateWithoutUserInput, Prisma.BuyerStatsUncheckedCreateWithoutUserInput>
}

export type BuyerStatsUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.BuyerStatsUpdateWithoutUserInput, Prisma.BuyerStatsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BuyerStatsCreateWithoutUserInput, Prisma.BuyerStatsUncheckedCreateWithoutUserInput>
  where?: Prisma.BuyerStatsWhereInput
}

export type BuyerStatsUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.BuyerStatsWhereInput
  data: Prisma.XOR<Prisma.BuyerStatsUpdateWithoutUserInput, Prisma.BuyerStatsUncheckedUpdateWithoutUserInput>
}

export type BuyerStatsUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  purchases?: Prisma.IntFieldUpdateOperationsInput | number
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type BuyerStatsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  purchases?: Prisma.IntFieldUpdateOperationsInput | number
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type BuyerStatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  purchases?: boolean
  totalSpent?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buyerStats"]>

export type BuyerStatsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  purchases?: boolean
  totalSpent?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buyerStats"]>

export type BuyerStatsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  purchases?: boolean
  totalSpent?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buyerStats"]>

export type BuyerStatsSelectScalar = {
  id?: boolean
  userId?: boolean
  purchases?: boolean
  totalSpent?: boolean
}

export type BuyerStatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "purchases" | "totalSpent", ExtArgs["result"]["buyerStats"]>
export type BuyerStatsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BuyerStatsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BuyerStatsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BuyerStatsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BuyerStats"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    purchases: number
    totalSpent: number
  }, ExtArgs["result"]["buyerStats"]>
  composites: {}
}

export type BuyerStatsGetPayload<S extends boolean | null | undefined | BuyerStatsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload, S>

export type BuyerStatsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BuyerStatsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BuyerStatsCountAggregateInputType | true
  }

export interface BuyerStatsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BuyerStats'], meta: { name: 'BuyerStats' } }
  /**
   * Find zero or one BuyerStats that matches the filter.
   * @param {BuyerStatsFindUniqueArgs} args - Arguments to find a BuyerStats
   * @example
   * // Get one BuyerStats
   * const buyerStats = await prisma.buyerStats.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BuyerStatsFindUniqueArgs>(args: Prisma.SelectSubset<T, BuyerStatsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BuyerStats that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BuyerStatsFindUniqueOrThrowArgs} args - Arguments to find a BuyerStats
   * @example
   * // Get one BuyerStats
   * const buyerStats = await prisma.buyerStats.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BuyerStatsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BuyerStatsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuyerStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuyerStatsFindFirstArgs} args - Arguments to find a BuyerStats
   * @example
   * // Get one BuyerStats
   * const buyerStats = await prisma.buyerStats.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BuyerStatsFindFirstArgs>(args?: Prisma.SelectSubset<T, BuyerStatsFindFirstArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BuyerStats that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuyerStatsFindFirstOrThrowArgs} args - Arguments to find a BuyerStats
   * @example
   * // Get one BuyerStats
   * const buyerStats = await prisma.buyerStats.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BuyerStatsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BuyerStatsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BuyerStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuyerStatsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BuyerStats
   * const buyerStats = await prisma.buyerStats.findMany()
   * 
   * // Get first 10 BuyerStats
   * const buyerStats = await prisma.buyerStats.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const buyerStatsWithIdOnly = await prisma.buyerStats.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BuyerStatsFindManyArgs>(args?: Prisma.SelectSubset<T, BuyerStatsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BuyerStats.
   * @param {BuyerStatsCreateArgs} args - Arguments to create a BuyerStats.
   * @example
   * // Create one BuyerStats
   * const BuyerStats = await prisma.buyerStats.create({
   *   data: {
   *     // ... data to create a BuyerStats
   *   }
   * })
   * 
   */
  create<T extends BuyerStatsCreateArgs>(args: Prisma.SelectSubset<T, BuyerStatsCreateArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BuyerStats.
   * @param {BuyerStatsCreateManyArgs} args - Arguments to create many BuyerStats.
   * @example
   * // Create many BuyerStats
   * const buyerStats = await prisma.buyerStats.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BuyerStatsCreateManyArgs>(args?: Prisma.SelectSubset<T, BuyerStatsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BuyerStats and returns the data saved in the database.
   * @param {BuyerStatsCreateManyAndReturnArgs} args - Arguments to create many BuyerStats.
   * @example
   * // Create many BuyerStats
   * const buyerStats = await prisma.buyerStats.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BuyerStats and only return the `id`
   * const buyerStatsWithIdOnly = await prisma.buyerStats.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BuyerStatsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BuyerStatsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BuyerStats.
   * @param {BuyerStatsDeleteArgs} args - Arguments to delete one BuyerStats.
   * @example
   * // Delete one BuyerStats
   * const BuyerStats = await prisma.buyerStats.delete({
   *   where: {
   *     // ... filter to delete one BuyerStats
   *   }
   * })
   * 
   */
  delete<T extends BuyerStatsDeleteArgs>(args: Prisma.SelectSubset<T, BuyerStatsDeleteArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BuyerStats.
   * @param {BuyerStatsUpdateArgs} args - Arguments to update one BuyerStats.
   * @example
   * // Update one BuyerStats
   * const buyerStats = await prisma.buyerStats.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BuyerStatsUpdateArgs>(args: Prisma.SelectSubset<T, BuyerStatsUpdateArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BuyerStats.
   * @param {BuyerStatsDeleteManyArgs} args - Arguments to filter BuyerStats to delete.
   * @example
   * // Delete a few BuyerStats
   * const { count } = await prisma.buyerStats.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BuyerStatsDeleteManyArgs>(args?: Prisma.SelectSubset<T, BuyerStatsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuyerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuyerStatsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BuyerStats
   * const buyerStats = await prisma.buyerStats.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BuyerStatsUpdateManyArgs>(args: Prisma.SelectSubset<T, BuyerStatsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BuyerStats and returns the data updated in the database.
   * @param {BuyerStatsUpdateManyAndReturnArgs} args - Arguments to update many BuyerStats.
   * @example
   * // Update many BuyerStats
   * const buyerStats = await prisma.buyerStats.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BuyerStats and only return the `id`
   * const buyerStatsWithIdOnly = await prisma.buyerStats.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BuyerStatsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BuyerStatsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BuyerStats.
   * @param {BuyerStatsUpsertArgs} args - Arguments to update or create a BuyerStats.
   * @example
   * // Update or create a BuyerStats
   * const buyerStats = await prisma.buyerStats.upsert({
   *   create: {
   *     // ... data to create a BuyerStats
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BuyerStats we want to update
   *   }
   * })
   */
  upsert<T extends BuyerStatsUpsertArgs>(args: Prisma.SelectSubset<T, BuyerStatsUpsertArgs<ExtArgs>>): Prisma.Prisma__BuyerStatsClient<runtime.Types.Result.GetResult<Prisma.$BuyerStatsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BuyerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuyerStatsCountArgs} args - Arguments to filter BuyerStats to count.
   * @example
   * // Count the number of BuyerStats
   * const count = await prisma.buyerStats.count({
   *   where: {
   *     // ... the filter for the BuyerStats we want to count
   *   }
   * })
  **/
  count<T extends BuyerStatsCountArgs>(
    args?: Prisma.Subset<T, BuyerStatsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BuyerStatsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BuyerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuyerStatsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BuyerStatsAggregateArgs>(args: Prisma.Subset<T, BuyerStatsAggregateArgs>): Prisma.PrismaPromise<GetBuyerStatsAggregateType<T>>

  /**
   * Group by BuyerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuyerStatsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BuyerStatsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BuyerStatsGroupByArgs['orderBy'] }
      : { orderBy?: BuyerStatsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BuyerStatsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBuyerStatsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BuyerStats model
 */
readonly fields: BuyerStatsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BuyerStats.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BuyerStatsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BuyerStats model
 */
export interface BuyerStatsFieldRefs {
  readonly id: Prisma.FieldRef<"BuyerStats", 'String'>
  readonly userId: Prisma.FieldRef<"BuyerStats", 'String'>
  readonly purchases: Prisma.FieldRef<"BuyerStats", 'Int'>
  readonly totalSpent: Prisma.FieldRef<"BuyerStats", 'Float'>
}
    

// Custom InputTypes
/**
 * BuyerStats findUnique
 */
export type BuyerStatsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * Filter, which BuyerStats to fetch.
   */
  where: Prisma.BuyerStatsWhereUniqueInput
}

/**
 * BuyerStats findUniqueOrThrow
 */
export type BuyerStatsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * Filter, which BuyerStats to fetch.
   */
  where: Prisma.BuyerStatsWhereUniqueInput
}

/**
 * BuyerStats findFirst
 */
export type BuyerStatsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * Filter, which BuyerStats to fetch.
   */
  where?: Prisma.BuyerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuyerStats to fetch.
   */
  orderBy?: Prisma.BuyerStatsOrderByWithRelationInput | Prisma.BuyerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuyerStats.
   */
  cursor?: Prisma.BuyerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuyerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuyerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuyerStats.
   */
  distinct?: Prisma.BuyerStatsScalarFieldEnum | Prisma.BuyerStatsScalarFieldEnum[]
}

/**
 * BuyerStats findFirstOrThrow
 */
export type BuyerStatsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * Filter, which BuyerStats to fetch.
   */
  where?: Prisma.BuyerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuyerStats to fetch.
   */
  orderBy?: Prisma.BuyerStatsOrderByWithRelationInput | Prisma.BuyerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BuyerStats.
   */
  cursor?: Prisma.BuyerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuyerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuyerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BuyerStats.
   */
  distinct?: Prisma.BuyerStatsScalarFieldEnum | Prisma.BuyerStatsScalarFieldEnum[]
}

/**
 * BuyerStats findMany
 */
export type BuyerStatsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * Filter, which BuyerStats to fetch.
   */
  where?: Prisma.BuyerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BuyerStats to fetch.
   */
  orderBy?: Prisma.BuyerStatsOrderByWithRelationInput | Prisma.BuyerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BuyerStats.
   */
  cursor?: Prisma.BuyerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BuyerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BuyerStats.
   */
  skip?: number
  distinct?: Prisma.BuyerStatsScalarFieldEnum | Prisma.BuyerStatsScalarFieldEnum[]
}

/**
 * BuyerStats create
 */
export type BuyerStatsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * The data needed to create a BuyerStats.
   */
  data: Prisma.XOR<Prisma.BuyerStatsCreateInput, Prisma.BuyerStatsUncheckedCreateInput>
}

/**
 * BuyerStats createMany
 */
export type BuyerStatsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BuyerStats.
   */
  data: Prisma.BuyerStatsCreateManyInput | Prisma.BuyerStatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BuyerStats createManyAndReturn
 */
export type BuyerStatsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * The data used to create many BuyerStats.
   */
  data: Prisma.BuyerStatsCreateManyInput | Prisma.BuyerStatsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BuyerStats update
 */
export type BuyerStatsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * The data needed to update a BuyerStats.
   */
  data: Prisma.XOR<Prisma.BuyerStatsUpdateInput, Prisma.BuyerStatsUncheckedUpdateInput>
  /**
   * Choose, which BuyerStats to update.
   */
  where: Prisma.BuyerStatsWhereUniqueInput
}

/**
 * BuyerStats updateMany
 */
export type BuyerStatsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BuyerStats.
   */
  data: Prisma.XOR<Prisma.BuyerStatsUpdateManyMutationInput, Prisma.BuyerStatsUncheckedUpdateManyInput>
  /**
   * Filter which BuyerStats to update
   */
  where?: Prisma.BuyerStatsWhereInput
  /**
   * Limit how many BuyerStats to update.
   */
  limit?: number
}

/**
 * BuyerStats updateManyAndReturn
 */
export type BuyerStatsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * The data used to update BuyerStats.
   */
  data: Prisma.XOR<Prisma.BuyerStatsUpdateManyMutationInput, Prisma.BuyerStatsUncheckedUpdateManyInput>
  /**
   * Filter which BuyerStats to update
   */
  where?: Prisma.BuyerStatsWhereInput
  /**
   * Limit how many BuyerStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BuyerStats upsert
 */
export type BuyerStatsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * The filter to search for the BuyerStats to update in case it exists.
   */
  where: Prisma.BuyerStatsWhereUniqueInput
  /**
   * In case the BuyerStats found by the `where` argument doesn't exist, create a new BuyerStats with this data.
   */
  create: Prisma.XOR<Prisma.BuyerStatsCreateInput, Prisma.BuyerStatsUncheckedCreateInput>
  /**
   * In case the BuyerStats was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BuyerStatsUpdateInput, Prisma.BuyerStatsUncheckedUpdateInput>
}

/**
 * BuyerStats delete
 */
export type BuyerStatsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
  /**
   * Filter which BuyerStats to delete.
   */
  where: Prisma.BuyerStatsWhereUniqueInput
}

/**
 * BuyerStats deleteMany
 */
export type BuyerStatsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BuyerStats to delete
   */
  where?: Prisma.BuyerStatsWhereInput
  /**
   * Limit how many BuyerStats to delete.
   */
  limit?: number
}

/**
 * BuyerStats without action
 */
export type BuyerStatsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuyerStats
   */
  select?: Prisma.BuyerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BuyerStats
   */
  omit?: Prisma.BuyerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuyerStatsInclude<ExtArgs> | null
}
