
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SellerStats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SellerStats
 * 
 */
export type SellerStatsModel = runtime.Types.Result.DefaultSelection<Prisma.$SellerStatsPayload>

export type AggregateSellerStats = {
  _count: SellerStatsCountAggregateOutputType | null
  _avg: SellerStatsAvgAggregateOutputType | null
  _sum: SellerStatsSumAggregateOutputType | null
  _min: SellerStatsMinAggregateOutputType | null
  _max: SellerStatsMaxAggregateOutputType | null
}

export type SellerStatsAvgAggregateOutputType = {
  rating: number | null
  totalSales: number | null
  responseTime: number | null
}

export type SellerStatsSumAggregateOutputType = {
  rating: number | null
  totalSales: number | null
  responseTime: number | null
}

export type SellerStatsMinAggregateOutputType = {
  id: string | null
  userId: string | null
  rating: number | null
  totalSales: number | null
  responseTime: number | null
  location: string | null
  description: string | null
}

export type SellerStatsMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  rating: number | null
  totalSales: number | null
  responseTime: number | null
  location: string | null
  description: string | null
}

export type SellerStatsCountAggregateOutputType = {
  id: number
  userId: number
  rating: number
  totalSales: number
  responseTime: number
  location: number
  description: number
  _all: number
}


export type SellerStatsAvgAggregateInputType = {
  rating?: true
  totalSales?: true
  responseTime?: true
}

export type SellerStatsSumAggregateInputType = {
  rating?: true
  totalSales?: true
  responseTime?: true
}

export type SellerStatsMinAggregateInputType = {
  id?: true
  userId?: true
  rating?: true
  totalSales?: true
  responseTime?: true
  location?: true
  description?: true
}

export type SellerStatsMaxAggregateInputType = {
  id?: true
  userId?: true
  rating?: true
  totalSales?: true
  responseTime?: true
  location?: true
  description?: true
}

export type SellerStatsCountAggregateInputType = {
  id?: true
  userId?: true
  rating?: true
  totalSales?: true
  responseTime?: true
  location?: true
  description?: true
  _all?: true
}

export type SellerStatsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SellerStats to aggregate.
   */
  where?: Prisma.SellerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerStats to fetch.
   */
  orderBy?: Prisma.SellerStatsOrderByWithRelationInput | Prisma.SellerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SellerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SellerStats
  **/
  _count?: true | SellerStatsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SellerStatsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SellerStatsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SellerStatsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SellerStatsMaxAggregateInputType
}

export type GetSellerStatsAggregateType<T extends SellerStatsAggregateArgs> = {
      [P in keyof T & keyof AggregateSellerStats]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSellerStats[P]>
    : Prisma.GetScalarType<T[P], AggregateSellerStats[P]>
}




export type SellerStatsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SellerStatsWhereInput
  orderBy?: Prisma.SellerStatsOrderByWithAggregationInput | Prisma.SellerStatsOrderByWithAggregationInput[]
  by: Prisma.SellerStatsScalarFieldEnum[] | Prisma.SellerStatsScalarFieldEnum
  having?: Prisma.SellerStatsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SellerStatsCountAggregateInputType | true
  _avg?: SellerStatsAvgAggregateInputType
  _sum?: SellerStatsSumAggregateInputType
  _min?: SellerStatsMinAggregateInputType
  _max?: SellerStatsMaxAggregateInputType
}

export type SellerStatsGroupByOutputType = {
  id: string
  userId: string
  rating: number
  totalSales: number
  responseTime: number
  location: string | null
  description: string | null
  _count: SellerStatsCountAggregateOutputType | null
  _avg: SellerStatsAvgAggregateOutputType | null
  _sum: SellerStatsSumAggregateOutputType | null
  _min: SellerStatsMinAggregateOutputType | null
  _max: SellerStatsMaxAggregateOutputType | null
}

type GetSellerStatsGroupByPayload<T extends SellerStatsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SellerStatsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SellerStatsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SellerStatsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SellerStatsGroupByOutputType[P]>
      }
    >
  >



export type SellerStatsWhereInput = {
  AND?: Prisma.SellerStatsWhereInput | Prisma.SellerStatsWhereInput[]
  OR?: Prisma.SellerStatsWhereInput[]
  NOT?: Prisma.SellerStatsWhereInput | Prisma.SellerStatsWhereInput[]
  id?: Prisma.StringFilter<"SellerStats"> | string
  userId?: Prisma.StringFilter<"SellerStats"> | string
  rating?: Prisma.FloatFilter<"SellerStats"> | number
  totalSales?: Prisma.IntFilter<"SellerStats"> | number
  responseTime?: Prisma.FloatFilter<"SellerStats"> | number
  location?: Prisma.StringNullableFilter<"SellerStats"> | string | null
  description?: Prisma.StringNullableFilter<"SellerStats"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SellerStatsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type SellerStatsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.SellerStatsWhereInput | Prisma.SellerStatsWhereInput[]
  OR?: Prisma.SellerStatsWhereInput[]
  NOT?: Prisma.SellerStatsWhereInput | Prisma.SellerStatsWhereInput[]
  rating?: Prisma.FloatFilter<"SellerStats"> | number
  totalSales?: Prisma.IntFilter<"SellerStats"> | number
  responseTime?: Prisma.FloatFilter<"SellerStats"> | number
  location?: Prisma.StringNullableFilter<"SellerStats"> | string | null
  description?: Prisma.StringNullableFilter<"SellerStats"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId">

export type SellerStatsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SellerStatsCountOrderByAggregateInput
  _avg?: Prisma.SellerStatsAvgOrderByAggregateInput
  _max?: Prisma.SellerStatsMaxOrderByAggregateInput
  _min?: Prisma.SellerStatsMinOrderByAggregateInput
  _sum?: Prisma.SellerStatsSumOrderByAggregateInput
}

export type SellerStatsScalarWhereWithAggregatesInput = {
  AND?: Prisma.SellerStatsScalarWhereWithAggregatesInput | Prisma.SellerStatsScalarWhereWithAggregatesInput[]
  OR?: Prisma.SellerStatsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SellerStatsScalarWhereWithAggregatesInput | Prisma.SellerStatsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SellerStats"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SellerStats"> | string
  rating?: Prisma.FloatWithAggregatesFilter<"SellerStats"> | number
  totalSales?: Prisma.IntWithAggregatesFilter<"SellerStats"> | number
  responseTime?: Prisma.FloatWithAggregatesFilter<"SellerStats"> | number
  location?: Prisma.StringNullableWithAggregatesFilter<"SellerStats"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"SellerStats"> | string | null
}

export type SellerStatsCreateInput = {
  id?: string
  rating?: number
  totalSales?: number
  responseTime?: number
  location?: string | null
  description?: string | null
  user: Prisma.UserCreateNestedOneWithoutSellerStatsInput
}

export type SellerStatsUncheckedCreateInput = {
  id?: string
  userId: string
  rating?: number
  totalSales?: number
  responseTime?: number
  location?: string | null
  description?: string | null
}

export type SellerStatsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalSales?: Prisma.IntFieldUpdateOperationsInput | number
  responseTime?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutSellerStatsNestedInput
}

export type SellerStatsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalSales?: Prisma.IntFieldUpdateOperationsInput | number
  responseTime?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SellerStatsCreateManyInput = {
  id?: string
  userId: string
  rating?: number
  totalSales?: number
  responseTime?: number
  location?: string | null
  description?: string | null
}

export type SellerStatsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalSales?: Prisma.IntFieldUpdateOperationsInput | number
  responseTime?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SellerStatsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalSales?: Prisma.IntFieldUpdateOperationsInput | number
  responseTime?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SellerStatsNullableScalarRelationFilter = {
  is?: Prisma.SellerStatsWhereInput | null
  isNot?: Prisma.SellerStatsWhereInput | null
}

export type SellerStatsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  location?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type SellerStatsAvgOrderByAggregateInput = {
  rating?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
}

export type SellerStatsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  location?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type SellerStatsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
  location?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type SellerStatsSumOrderByAggregateInput = {
  rating?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  responseTime?: Prisma.SortOrder
}

export type SellerStatsCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SellerStatsCreateWithoutUserInput, Prisma.SellerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.SellerStatsCreateOrConnectWithoutUserInput
  connect?: Prisma.SellerStatsWhereUniqueInput
}

export type SellerStatsUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SellerStatsCreateWithoutUserInput, Prisma.SellerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.SellerStatsCreateOrConnectWithoutUserInput
  connect?: Prisma.SellerStatsWhereUniqueInput
}

export type SellerStatsUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SellerStatsCreateWithoutUserInput, Prisma.SellerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.SellerStatsCreateOrConnectWithoutUserInput
  upsert?: Prisma.SellerStatsUpsertWithoutUserInput
  disconnect?: Prisma.SellerStatsWhereInput | boolean
  delete?: Prisma.SellerStatsWhereInput | boolean
  connect?: Prisma.SellerStatsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SellerStatsUpdateToOneWithWhereWithoutUserInput, Prisma.SellerStatsUpdateWithoutUserInput>, Prisma.SellerStatsUncheckedUpdateWithoutUserInput>
}

export type SellerStatsUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SellerStatsCreateWithoutUserInput, Prisma.SellerStatsUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.SellerStatsCreateOrConnectWithoutUserInput
  upsert?: Prisma.SellerStatsUpsertWithoutUserInput
  disconnect?: Prisma.SellerStatsWhereInput | boolean
  delete?: Prisma.SellerStatsWhereInput | boolean
  connect?: Prisma.SellerStatsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SellerStatsUpdateToOneWithWhereWithoutUserInput, Prisma.SellerStatsUpdateWithoutUserInput>, Prisma.SellerStatsUncheckedUpdateWithoutUserInput>
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SellerStatsCreateWithoutUserInput = {
  id?: string
  rating?: number
  totalSales?: number
  responseTime?: number
  location?: string | null
  description?: string | null
}

export type SellerStatsUncheckedCreateWithoutUserInput = {
  id?: string
  rating?: number
  totalSales?: number
  responseTime?: number
  location?: string | null
  description?: string | null
}

export type SellerStatsCreateOrConnectWithoutUserInput = {
  where: Prisma.SellerStatsWhereUniqueInput
  create: Prisma.XOR<Prisma.SellerStatsCreateWithoutUserInput, Prisma.SellerStatsUncheckedCreateWithoutUserInput>
}

export type SellerStatsUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.SellerStatsUpdateWithoutUserInput, Prisma.SellerStatsUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SellerStatsCreateWithoutUserInput, Prisma.SellerStatsUncheckedCreateWithoutUserInput>
  where?: Prisma.SellerStatsWhereInput
}

export type SellerStatsUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.SellerStatsWhereInput
  data: Prisma.XOR<Prisma.SellerStatsUpdateWithoutUserInput, Prisma.SellerStatsUncheckedUpdateWithoutUserInput>
}

export type SellerStatsUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalSales?: Prisma.IntFieldUpdateOperationsInput | number
  responseTime?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SellerStatsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalSales?: Prisma.IntFieldUpdateOperationsInput | number
  responseTime?: Prisma.FloatFieldUpdateOperationsInput | number
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type SellerStatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  rating?: boolean
  totalSales?: boolean
  responseTime?: boolean
  location?: boolean
  description?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sellerStats"]>

export type SellerStatsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  rating?: boolean
  totalSales?: boolean
  responseTime?: boolean
  location?: boolean
  description?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sellerStats"]>

export type SellerStatsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  rating?: boolean
  totalSales?: boolean
  responseTime?: boolean
  location?: boolean
  description?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sellerStats"]>

export type SellerStatsSelectScalar = {
  id?: boolean
  userId?: boolean
  rating?: boolean
  totalSales?: boolean
  responseTime?: boolean
  location?: boolean
  description?: boolean
}

export type SellerStatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "rating" | "totalSales" | "responseTime" | "location" | "description", ExtArgs["result"]["sellerStats"]>
export type SellerStatsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SellerStatsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SellerStatsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SellerStatsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SellerStats"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    rating: number
    totalSales: number
    responseTime: number
    location: string | null
    description: string | null
  }, ExtArgs["result"]["sellerStats"]>
  composites: {}
}

export type SellerStatsGetPayload<S extends boolean | null | undefined | SellerStatsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload, S>

export type SellerStatsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SellerStatsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SellerStatsCountAggregateInputType | true
  }

export interface SellerStatsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SellerStats'], meta: { name: 'SellerStats' } }
  /**
   * Find zero or one SellerStats that matches the filter.
   * @param {SellerStatsFindUniqueArgs} args - Arguments to find a SellerStats
   * @example
   * // Get one SellerStats
   * const sellerStats = await prisma.sellerStats.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SellerStatsFindUniqueArgs>(args: Prisma.SelectSubset<T, SellerStatsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SellerStats that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SellerStatsFindUniqueOrThrowArgs} args - Arguments to find a SellerStats
   * @example
   * // Get one SellerStats
   * const sellerStats = await prisma.sellerStats.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SellerStatsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SellerStatsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SellerStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerStatsFindFirstArgs} args - Arguments to find a SellerStats
   * @example
   * // Get one SellerStats
   * const sellerStats = await prisma.sellerStats.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SellerStatsFindFirstArgs>(args?: Prisma.SelectSubset<T, SellerStatsFindFirstArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SellerStats that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerStatsFindFirstOrThrowArgs} args - Arguments to find a SellerStats
   * @example
   * // Get one SellerStats
   * const sellerStats = await prisma.sellerStats.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SellerStatsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SellerStatsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SellerStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerStatsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SellerStats
   * const sellerStats = await prisma.sellerStats.findMany()
   * 
   * // Get first 10 SellerStats
   * const sellerStats = await prisma.sellerStats.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sellerStatsWithIdOnly = await prisma.sellerStats.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SellerStatsFindManyArgs>(args?: Prisma.SelectSubset<T, SellerStatsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SellerStats.
   * @param {SellerStatsCreateArgs} args - Arguments to create a SellerStats.
   * @example
   * // Create one SellerStats
   * const SellerStats = await prisma.sellerStats.create({
   *   data: {
   *     // ... data to create a SellerStats
   *   }
   * })
   * 
   */
  create<T extends SellerStatsCreateArgs>(args: Prisma.SelectSubset<T, SellerStatsCreateArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SellerStats.
   * @param {SellerStatsCreateManyArgs} args - Arguments to create many SellerStats.
   * @example
   * // Create many SellerStats
   * const sellerStats = await prisma.sellerStats.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SellerStatsCreateManyArgs>(args?: Prisma.SelectSubset<T, SellerStatsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SellerStats and returns the data saved in the database.
   * @param {SellerStatsCreateManyAndReturnArgs} args - Arguments to create many SellerStats.
   * @example
   * // Create many SellerStats
   * const sellerStats = await prisma.sellerStats.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SellerStats and only return the `id`
   * const sellerStatsWithIdOnly = await prisma.sellerStats.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SellerStatsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SellerStatsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SellerStats.
   * @param {SellerStatsDeleteArgs} args - Arguments to delete one SellerStats.
   * @example
   * // Delete one SellerStats
   * const SellerStats = await prisma.sellerStats.delete({
   *   where: {
   *     // ... filter to delete one SellerStats
   *   }
   * })
   * 
   */
  delete<T extends SellerStatsDeleteArgs>(args: Prisma.SelectSubset<T, SellerStatsDeleteArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SellerStats.
   * @param {SellerStatsUpdateArgs} args - Arguments to update one SellerStats.
   * @example
   * // Update one SellerStats
   * const sellerStats = await prisma.sellerStats.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SellerStatsUpdateArgs>(args: Prisma.SelectSubset<T, SellerStatsUpdateArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SellerStats.
   * @param {SellerStatsDeleteManyArgs} args - Arguments to filter SellerStats to delete.
   * @example
   * // Delete a few SellerStats
   * const { count } = await prisma.sellerStats.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SellerStatsDeleteManyArgs>(args?: Prisma.SelectSubset<T, SellerStatsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SellerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerStatsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SellerStats
   * const sellerStats = await prisma.sellerStats.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SellerStatsUpdateManyArgs>(args: Prisma.SelectSubset<T, SellerStatsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SellerStats and returns the data updated in the database.
   * @param {SellerStatsUpdateManyAndReturnArgs} args - Arguments to update many SellerStats.
   * @example
   * // Update many SellerStats
   * const sellerStats = await prisma.sellerStats.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SellerStats and only return the `id`
   * const sellerStatsWithIdOnly = await prisma.sellerStats.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SellerStatsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SellerStatsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SellerStats.
   * @param {SellerStatsUpsertArgs} args - Arguments to update or create a SellerStats.
   * @example
   * // Update or create a SellerStats
   * const sellerStats = await prisma.sellerStats.upsert({
   *   create: {
   *     // ... data to create a SellerStats
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SellerStats we want to update
   *   }
   * })
   */
  upsert<T extends SellerStatsUpsertArgs>(args: Prisma.SelectSubset<T, SellerStatsUpsertArgs<ExtArgs>>): Prisma.Prisma__SellerStatsClient<runtime.Types.Result.GetResult<Prisma.$SellerStatsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SellerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerStatsCountArgs} args - Arguments to filter SellerStats to count.
   * @example
   * // Count the number of SellerStats
   * const count = await prisma.sellerStats.count({
   *   where: {
   *     // ... the filter for the SellerStats we want to count
   *   }
   * })
  **/
  count<T extends SellerStatsCountArgs>(
    args?: Prisma.Subset<T, SellerStatsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SellerStatsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SellerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerStatsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SellerStatsAggregateArgs>(args: Prisma.Subset<T, SellerStatsAggregateArgs>): Prisma.PrismaPromise<GetSellerStatsAggregateType<T>>

  /**
   * Group by SellerStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SellerStatsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SellerStatsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SellerStatsGroupByArgs['orderBy'] }
      : { orderBy?: SellerStatsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SellerStatsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSellerStatsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SellerStats model
 */
readonly fields: SellerStatsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SellerStats.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SellerStatsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SellerStats model
 */
export interface SellerStatsFieldRefs {
  readonly id: Prisma.FieldRef<"SellerStats", 'String'>
  readonly userId: Prisma.FieldRef<"SellerStats", 'String'>
  readonly rating: Prisma.FieldRef<"SellerStats", 'Float'>
  readonly totalSales: Prisma.FieldRef<"SellerStats", 'Int'>
  readonly responseTime: Prisma.FieldRef<"SellerStats", 'Float'>
  readonly location: Prisma.FieldRef<"SellerStats", 'String'>
  readonly description: Prisma.FieldRef<"SellerStats", 'String'>
}
    

// Custom InputTypes
/**
 * SellerStats findUnique
 */
export type SellerStatsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * Filter, which SellerStats to fetch.
   */
  where: Prisma.SellerStatsWhereUniqueInput
}

/**
 * SellerStats findUniqueOrThrow
 */
export type SellerStatsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * Filter, which SellerStats to fetch.
   */
  where: Prisma.SellerStatsWhereUniqueInput
}

/**
 * SellerStats findFirst
 */
export type SellerStatsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * Filter, which SellerStats to fetch.
   */
  where?: Prisma.SellerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerStats to fetch.
   */
  orderBy?: Prisma.SellerStatsOrderByWithRelationInput | Prisma.SellerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SellerStats.
   */
  cursor?: Prisma.SellerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SellerStats.
   */
  distinct?: Prisma.SellerStatsScalarFieldEnum | Prisma.SellerStatsScalarFieldEnum[]
}

/**
 * SellerStats findFirstOrThrow
 */
export type SellerStatsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * Filter, which SellerStats to fetch.
   */
  where?: Prisma.SellerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerStats to fetch.
   */
  orderBy?: Prisma.SellerStatsOrderByWithRelationInput | Prisma.SellerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SellerStats.
   */
  cursor?: Prisma.SellerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SellerStats.
   */
  distinct?: Prisma.SellerStatsScalarFieldEnum | Prisma.SellerStatsScalarFieldEnum[]
}

/**
 * SellerStats findMany
 */
export type SellerStatsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * Filter, which SellerStats to fetch.
   */
  where?: Prisma.SellerStatsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SellerStats to fetch.
   */
  orderBy?: Prisma.SellerStatsOrderByWithRelationInput | Prisma.SellerStatsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SellerStats.
   */
  cursor?: Prisma.SellerStatsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SellerStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SellerStats.
   */
  skip?: number
  distinct?: Prisma.SellerStatsScalarFieldEnum | Prisma.SellerStatsScalarFieldEnum[]
}

/**
 * SellerStats create
 */
export type SellerStatsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * The data needed to create a SellerStats.
   */
  data: Prisma.XOR<Prisma.SellerStatsCreateInput, Prisma.SellerStatsUncheckedCreateInput>
}

/**
 * SellerStats createMany
 */
export type SellerStatsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SellerStats.
   */
  data: Prisma.SellerStatsCreateManyInput | Prisma.SellerStatsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SellerStats createManyAndReturn
 */
export type SellerStatsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * The data used to create many SellerStats.
   */
  data: Prisma.SellerStatsCreateManyInput | Prisma.SellerStatsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SellerStats update
 */
export type SellerStatsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * The data needed to update a SellerStats.
   */
  data: Prisma.XOR<Prisma.SellerStatsUpdateInput, Prisma.SellerStatsUncheckedUpdateInput>
  /**
   * Choose, which SellerStats to update.
   */
  where: Prisma.SellerStatsWhereUniqueInput
}

/**
 * SellerStats updateMany
 */
export type SellerStatsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SellerStats.
   */
  data: Prisma.XOR<Prisma.SellerStatsUpdateManyMutationInput, Prisma.SellerStatsUncheckedUpdateManyInput>
  /**
   * Filter which SellerStats to update
   */
  where?: Prisma.SellerStatsWhereInput
  /**
   * Limit how many SellerStats to update.
   */
  limit?: number
}

/**
 * SellerStats updateManyAndReturn
 */
export type SellerStatsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * The data used to update SellerStats.
   */
  data: Prisma.XOR<Prisma.SellerStatsUpdateManyMutationInput, Prisma.SellerStatsUncheckedUpdateManyInput>
  /**
   * Filter which SellerStats to update
   */
  where?: Prisma.SellerStatsWhereInput
  /**
   * Limit how many SellerStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SellerStats upsert
 */
export type SellerStatsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * The filter to search for the SellerStats to update in case it exists.
   */
  where: Prisma.SellerStatsWhereUniqueInput
  /**
   * In case the SellerStats found by the `where` argument doesn't exist, create a new SellerStats with this data.
   */
  create: Prisma.XOR<Prisma.SellerStatsCreateInput, Prisma.SellerStatsUncheckedCreateInput>
  /**
   * In case the SellerStats was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SellerStatsUpdateInput, Prisma.SellerStatsUncheckedUpdateInput>
}

/**
 * SellerStats delete
 */
export type SellerStatsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
  /**
   * Filter which SellerStats to delete.
   */
  where: Prisma.SellerStatsWhereUniqueInput
}

/**
 * SellerStats deleteMany
 */
export type SellerStatsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SellerStats to delete
   */
  where?: Prisma.SellerStatsWhereInput
  /**
   * Limit how many SellerStats to delete.
   */
  limit?: number
}

/**
 * SellerStats without action
 */
export type SellerStatsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SellerStats
   */
  select?: Prisma.SellerStatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SellerStats
   */
  omit?: Prisma.SellerStatsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SellerStatsInclude<ExtArgs> | null
}
